apiVersion: v1
kind: ConfigMap
metadata:
  name: smf-configmap
data:
  smfcfg.conf: |
    info:
      version: 1.0.0
      description: AMF initial local configuration
    
    configuration:
      smfName: SMF
      sbi:
        scheme: https
        ipv4Addr: {{ .Values.http.addr }}
        port: 29502
        tls:
          key: free5gc/support/TLS/smf.key
          pem: free5gc/support/TLS/smf.pem
      serviceNameList:
        - nsmf-pdusession
        - nsmf-event-exposure
      pfcp:
        addr: {{ .Values.pfcp.addr }}
      upf:
        - addr: {{ .Values.pfcp.upfAddr }}
      ue_subnet: 60.60.0.0/16
      nrfUri: https://{{ .Values.global.nrfAddr }}:29510
