apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mininet.fullname" . }}
  labels:
    {{- include "mininet.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mininet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mininet.selectorLabels" . | nindent 8 }}
      annotations:
        k8s.v1.cni.cncf.io/networks: mn-enb-bridge-net,mn-upf-bridge-net
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "mininet.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["/toposcripts/{{ .Values.topo }}"]
          stdin: true
          tty: true
          env:
            - name: ONOS_WEB_USER
              value: onos
            - name: ONOS_WEB_PASS
              value: rocks
          volumeMounts:
            - name: topo-scripts
              mountPath: /toposcripts/{{ .Values.topo }}
              subPath: {{ .Values.topo }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: topo-scripts
          configMap:
            name: toposcripts-configmap
            defaultMode: 0755
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
