# Default values for free5gc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  dbUri: mongodb://mongo.default.svc.cluster.local/free5gc
  freediameter:
    amf:
      addr: 192.168.2.2
    hss:
      addr: 192.168.2.3
    smf:
      addr: 192.168.2.4
    pcrf:
      addr: 192.168.2.5
  enableMininet: false

amf:
  http:
    addr: 192.168.2.2
  s1ap:
    addr: 192.168.2.2

hss:
  addr: 192.168.2.3

smf:
  addr: 192.168.2.4

pcrf:
  addr: 192.168.2.5

upf:
  pfcp:
    addr: 192.168.2.6
  gtpu:
    addr: 192.168.2.6
