apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "amf.fullname" . }}
  labels:
    {{- include "amf.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "amf.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "amf.selectorLabels" . | nindent 8 }}
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"{{ .Values.http.addr }}\"]"
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash"]
          args: ["-c", "/usr/src/free5gc-stage-1/free5gc-amfd"]
          stdin: true
          tty: true
          ports:
            - name: sctp
              containerPort: 36412
              protocol: SCTP
          volumeMounts:
            - name: free5gc-config
              mountPath: /usr/src/free5gc-stage-1/install/etc/free5gc/free5gc.conf
              subPath: free5gc.conf
            - name: amf-freediameter-config
              mountPath: /usr/src/free5gc-stage-1/install/etc/free5gc/freeDiameter/amf.conf
              subPath: amf.conf
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: free5gc-config
          configMap:
            name: free5gc-configmap
        - name: amf-freediameter-config
          configMap:
            name: amf-freediameter-configmap
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
