# Default values for webui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: steven30801/free5gc-webui
  tag: v1
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}

securityContext: {}

service:
  webuiServiceType: NodePort
  webui:
    port: 3000
    nodePort: 30300

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
