# global
global:
  image:
    free5gc:
      # the free5gc-private-build image is the unreleased version of free5GC repository
      repository: free5gc-private-build
      tag: latest
  nrf:
    addr: 192.168.2.4
  enableSlices: true
  numOfSlices: 3
  slices:
    1:
      - sst: 1
        sd: "010203"
    2:
      - sst: 1
        sd: "112233"
    3:
      - sst: 1
        sd: "102030"

# in free5gc chart
amf:
  http:
    addr: 192.168.2.2
  ngap:
    addr: 192.168.2.2

ausf:
  http:
    addr: 192.168.2.3

nrf:
  http:
    addr: 192.168.2.4

nssf:
  http:
    addr: 192.168.2.5

pcf:
  http:
    addr: 192.168.2.6

smf:
  http:
    addr: 192.168.2.7
  pfcp:
    addr: 192.168.2.7
  upf:
    pfcp:
      addr: 192.168.2.10
    gtpu:
      addr: 192.168.2.10
  gnb:
    addr: 192.168.2.11

udm:
  http:
    addr: 192.168.2.8
  udr:
    addr: 192.168.2.9

udr:
  http:
    addr: 192.168.2.9

upf:
  pfcp:
    addr: 192.168.2.10
  gtpu:
    addr: 192.168.2.10

ransim:
  addr: 192.168.2.11
  amf:
    ngap:
      addr: 192.168.2.2
