apiVersion: v1
kind: ConfigMap
metadata:
  name: udm-configmap
data:
  udmcfg.conf: |
    info:
      version: 1.0.0
      description: UDM initial local configuration
    
    configuration:
      serviceNameList:
        - nudm-sdm
        - nudm-uecm
        - nudm-ueau
        - nudm-ee
        - nudm-pp
      sbi:
        scheme: https
        ipv4Addr: {{ .Values.http.addr }}
        port: 29503
        tls:
          log: free5gc/udmsslkey.log
          pem: free5gc/support/TLS/udm.pem
          key: free5gc/support/TLS/udm.key
      
      udrclient:
        scheme: https
        ipv4Addr: {{ .Values.udr.addr }}
        port: 29504
    
      nrfclient:
        scheme: https
        ipv4Addr: {{ .Values.global.nrf.addr }}
        port: 29510
