{{- if .Values.global.enableMininet }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: upf-bridge-net
  annotations:
    "helm.sh/hook-weight": "-10"
spec:
  config: '{
    "name": "mn2",
    "type": "bridge",
    "bridge": "mn2",
    "ipam": {
      "type": "host-local",
      "subnet": "{{ .Values.global.mnUpfBridge.subnet }}",
      "routes": [
        {
          "dst": "{{ .Values.enbSubnet }}",
          "gw": "{{ .Values.global.mnEnbBridge.gateway }}"
        }
      ]
    },
    "args": {
      "cni": {
        "ips": ["{{ .Values.gtpu.addr }}"]
      }
    }
  }'
{{- end }}
