apiVersion: v1
kind: ConfigMap
metadata:
  name: nrf-configmap
data:
  nrfcfg.conf: |
    info:
      version: 1.0.0
      description: NRF initial local configuration
    
    configuration:
      MongoDBName: "free5gc"
      MongoDBUrl: "mongodb://{{ .Values.global.dbServiceDomain }}:27017"
      DefaultServiceIP: "{{ .Values.http.addr }}"
      sbi:
        scheme: https
        ipv4Addr: {{ .Values.http.addr }}
        port: 29510
      DefaultPlmnId:
        mcc: "208"
        mnc: "93"
      serviceNameList:
        - nnrf-nfm
        - nnrf-disc   
