apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "intel_sriov",
                "selectors": {
                    "pfName": ["enp1s0f0"]
                }
            }
        ]
    }
