apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "sriov_net",
                "selectors": {
                    "pfNames": ["PF_NAME#0-LAST_VF"]
                }
            }
        ]
    }
