# Default values for UDR.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  image:
    free5gc: {}

replicaCount: 1

image:
  repository: steven30801/free5gc-build
  tag: v2.0.2
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

http:
  addr: 192.168.2.9

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
