apiVersion: v1
kind: ConfigMap
metadata:
  name: amf-configmap
data:
  amfcfg.conf: |
    info:
      version: 1.0.0
      description: AMF initial local configuration
    
    configuration:
      amfName: AMF
      ngapIpList:
        - {{ .Values.ngap.addr }}
      sbi:
        scheme: https
        ipv4Addr: {{ .Values.http.addr }}
        port: 29518
      serviceNameList:
        - namf-comm
        - namf-evts
        - namf-mt
        - namf-loc
      servedGuamiList:
        - plmnId:
            mcc: 208
            mnc: 93
          amfId: cafe00
      supportTaiList:
        - plmnId:
            mcc: 208
            mnc: 93
          tac: 1
      plmnSupportList:
        - plmnId:
            mcc: 208
            mnc: 93
          snssaiList:
            - sst: 1
              sd: 010203
            - sst: 1
              sd: 112233
      supportDnnList:
        - internet
      nrfUri: https://{{ .Values.global.nrf.addr }}:29510
      security:
        integrityOrder:
          - NIA2
          - NIA0
        cipheringOrder:
          - NEA2
          - NEA0
      networkName:
        full: free5GC
        short: free
      t3502: 720
      t3512: 3600
      non3gppDeregistrationTimer: 3240
