# Default values for free5gc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  dbServiceDomain: mongo.default.svc.cluster.local
  nrfAddr: 192.168.2.4

amf:
  http:
    addr: 192.168.2.2
  ngap:
    addr: 192.168.2.2

ausf:
  http:
    addr: 192.168.2.3

nrf:
  http:
    addr: 192.168.2.4

nssf:
  http:
    addr: 192.168.2.5

pcf:
  http:
    addr: 192.168.2.6

smf:
  http:
    addr: 192.168.2.7
  pfcp:
    addr: 192.168.2.7
    upfAddr: 192.168.2.10

udm:
  http:
    addr: 192.168.2.8
    udrAddr: 192.168.2.9

udr:
  http:
    addr: 192.168.2.9

upf:
  pfcp:
    addr: 192.168.2.10
  gtpu:
    addr: 192.168.2.10
