{{- if .Values.global.enableSriov }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: upf-sriov-net
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/sriov_net
spec:
  config: '{
  "type": "sriov",
  "cniVersion": "0.3.1",
  "name": "upf-sriov",
  "ipam": {
    "type": "host-local",
    "subnet": "{{ .Values.gtpu.subnet }}"
  },
  "args": {
    "cni": {
      "ips": ["{{ .Values.gtpu.addr }}"]
    }
  }
}'
{{- end }}
