apiVersion: v1
kind: ConfigMap
metadata:
  name: webui-configmap
data:
  webuicfg.conf: |
    info:
      version: 1.0.0
      description: Web UI initial local configuration
    
    configuration:
      mongodb:
        name: free5gc
        url: mongodb://{{ .Values.global.dbServiceDomain }}:27017
