apiVersion: v1
kind: ConfigMap
metadata:
  name: ausf-configmap
data:
  ausfcfg.conf: |
    info:
      version: 1.0.0
      description: AUSF initial local configuration
    
    configuration:
      sbi:
        scheme: https
        ipv4Addr: {{ .Values.http.addr }}
        port: 29509
      serviceNameList:
        - nausf-auth
      nrfUri: https://{{ .Values.global.nrf.addr }}:29510
      plmnSupportList:
        - mcc: 208
          mnc: 93
        - mcc: 123
          mnc: 45
      groupId: ausfGroup001
